config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  root to: "pages#home"
  # Cart Routes

  get "contact", to: "contact_us#contact"
  get "add_contact", to: "contact_us#add_contact"
  get "wishlist", to: "wishlist#index"
  get "add_to_wishlist", to: "wishlist#add_to_wishlist"
  get "remove_item_from_wishlist", to: "wishlist#remove_item_from_wishlist"
  get "wishlist_add_to_cart", to: "wishlist#wishlist_add_to_cart"

  get "cart", to: "carts#cart", as: :cart
  get "single_product_add_to_cart", to: "carts#single_product_add_to_cart"
  get "add_to_cart/:id", to: "carts#add_to_cart", as: :add_to_cart
  get "remove_cart_product", to: "carts#remove_cart_product"
  get "increase_product_quantity", to: "carts#increase_product_quantity"
  get "decrease_product_quantity", to: "carts#decrease_product_quantity"
  get "non_on_hand_add_to_cart", to: "carts#non_on_hand_add_to_cart"
  get "delete_cart_product", to: "carts#delete_cart_product"
  get "get_sub_total", to: "carts#sub_totals"

  # Profile Routes
  get "profile", to: "profiles#profile"
  put "profile", to: "profiles#update_profile"

  # Calculator Routes
  get "calculator", to: "calculators#calculator"
  get "calculate", to: "calculators#calculate"

  # Pages Routes
  get "brand_category", to: "pages#brand_category"
  get "category", to: "pages#category"
  get "shipping_type", to: "pages#shipping_type"
  get "transaction_history", to: "pages#transaction_history"
  get "complete_purchase", to: "pages#complete_purchase"
  get "order_product/:id", to: "pages#order_product", as: :order_product
  get "product_info/:id", to: "pages#product_info", as: :product_info

  # Shipping Address Routes
  get "shipping_address", to: "shipping_address#index"
  get "states", to: "shipping_address#states"
  get "cities", to: "shipping_address#cities"
  get "save_shipping_address", to: "shipping_address#save_shipping_address"
end

app/views/pages/billing_address.html.haml
.container
  %br/
  .row
    .col-lg-3.col-md-3
    .col-lg-6.col-md-6
    .col-lg-3.col-md-3

app/views/pages/home.html.haml
= render 'devise/shared/carousel', carousels: @carousels
%section.wn__bestseller__area.bg--white.pt--80.pb--30
  %div.container
    = render 'devise/shared/portal'

app/views/pages/order_product.html.haml
= render 'devise/shared/page_directory', current_location: 'Order Product'
.container
  .row
    .col-md-8.col-lg-8.mb-5
      %br/
      .card
        .card-body
          .table-responsive.table-hover
            %table#shopping.table.product-table
              %thead.elegant-color
                %tr
                  %th.font-weight-bold
                    %strong Order ID
                  %th.font-weight-bold
                    %strong Image
                  %th.font-weight-bold
                    %strong Product
                  %th.font-weight-bold
                    %strong Subtotal
                %tbody.tbody-res
                - @order_products.each do |op|
                  %tr
                    %td
                      = op.try(:order_id)
                    %td
                      = image_tag op.product.try(:image).url || "cart_logo", class: 'img-thumbnail z-depth-0', width: 75, height: 75
                    %td
                      = op.product.try(:name)
                    %td
                      = "#{number_to_currency(op.sub_total / @exchange_rate, :unit => "$", :separator => ".", :delimiter => ",")}"
    .col-md-4.col-lg-4.mb-5
      %br/
      .card
        .card-body
          .table-responsive.table-hover
            %table#shopping.table.product-table
              %thead
                %tr
                  %td
                    %h4{ style: "color:gray" }
                      = "Exchange Rate:"
                  %td
                    %h4{ style: "color:gray" }
                      = "#{number_to_currency(@exchange_rate, :unit => "₱", :separator => ".", :delimiter => ",")}"      
                %tr
                  %td
                    %h4{ style: "color:gray" }
                      = "Subtotal: "
                  %td
                    %h4{ style: "color:gray" }
                      = "#{number_to_currency(@subtotal / @exchange_rate, :unit => "$", :separator => ".", :delimiter => ",")}"        
                %tr
                  %td
                    %h4{ style: "color:gray" }
                      = "Total: "
                  %td
                    %h4{ style: "color:gray" }
                      = "#{number_to_currency(@total / @exchange_rate, :unit => "₱", :separator => ".", :delimiter => ",")}"   
                    %br/
= stylesheet_link_tag  'cart.css'

app/views/pages/product_info.html.haml
= render 'devise/shared/page_directory', current_location: 'Shop Single'
.maincontent.bg--white.pt--80.pb--55
  .container
    .row
      .col-lg-9.col-12
        .wn__single__product
          .row
            .col-lg-6.col-12
              .wn__fotorama__wrapper
                .fotorama.wn__fotorama__action{"data-nav" => "thumbs"}
                  - @product_info.image_galleries.each do |pg|
                    %a{:href => "#{@product_info.image.image_galleries.to_s}"}
                      = image_tag @product_info.image.image_galleries.to_s, style: "width:450px!important;height:565px!important"
                    %a{:href => "#{pg.image.image_galleries.to_s}"}
                      = image_tag pg.image.image_galleries.to_s, style: "width:450px!important;height:565px!important"
            .col-lg-6.col-12
              .product__info__main
                %h1 
                  = @product_info.name if @product_info.name.present?
                -# .product-reviews-summary.d-flex
                  %ul.rating-summary.d-flex
                    %li
                      %i.zmdi.zmdi-star-outline
                    %li
                      %i.zmdi.zmdi-star-outline
                    %li
                      %i.zmdi.zmdi-star-outline
                    %li.off
                      %i.zmdi.zmdi-star-outline
                    %li.off
                      %i.zmdi.zmdi-star-outline
                .price-box
                  %span
                    = number_to_currency(@product_info.try(:price), :unit => "₱", :separator => ".", :delimiter => ",")
                .product__overview
                  %p 
                    = @product_info.try(:product_description) 
                .box-tocart.d-flex
                  %input#product_id{ value: "#{@product_info.id}", style: "display:none" }
                  %span Qty
                  %input#qty.input-text.qty{:min => "1", :name => "qty", :title => "Qty", :type => "number", :value => "1"}/
                  .addtocart__actions
                    %button.tocart{:title => "Add to Cart", :type => "submit", id: "add_to_cart"} Add to Cart
                    %br/ 
                    %br/
                    %button.tocart{:title => "Add to WishList", :type => "submit", style:"background-color:black", id: "add_to_wishlist"} Add to wishlist
                  -# .product-addto-links.clearfix
                  -#   %a.wishlist{:href => "#", style: "background:url('/assets/icons/button-wishlist.png');background-repeat:no-repeat;background-position:center"}
                    -# %a.compare{:href => "#"}
                .product_meta
                  %span.posted_in
                    Categories:
                    = succeed "," do
                      %a{:href => "#"} 
                        = @product_info.category.name

                .product-share
                  %ul
                    %li.categories-title Share :
                    %li
                      %a{:href => "#"}
                        %i.icon-social-twitter.icons
                    %li
                      %a{:href => "#"}
                        %i.icon-social-tumblr.icons
                    %li
                      %a{:href => "#"}
                        %i.icon-social-facebook.icons
                    %li
                      %a{:href => "#"}
                        %i.icon-social-linkedin.icons
        .product__info__detailed
= javascript_include_tag 'single_product.js'

app/views/pages/transaction_history.html.haml
= render 'devise/shared/page_directory', current_location: 'Transaction History'
.container
  .col-md-12.col-lg-12.mb-5
    %br/
    .card
      .card-body
        .table-responsive.table-hover
          %table#shopping.table.product-table
            / Table head
            %thead.elegant-color
              %tr
                %th.font-weight-bold
                  %strong Order ID
                %th.font-weight-bold
                  %strong Order Status
                %th.font-weight-bold
                  %strong Payment Status
                %th.font-weight-bold
                  %strong Total
                %th.font-weight-bold
                  %strong Down Payment
                %th.font-weight-bold
                  %strong Balance
                %th.font-weight-bold
                  %strong Action
            %tbody.tbody-res
              - @orders.each do |order|
                %tr
                  %td
                    = "0000-#{order.id}"
                  %td
                    = order.order_status.try(:name)
                  %td
                    = order.payment_order_status.try(:name)
                  %td
                    = "#{number_to_currency(order.try(:total), :unit => "₱", :separator => ".", :delimiter => ",")}"
                  %td
                    = "#{number_to_currency(order.try(:down_payment), :unit => "₱", :separator => ".", :delimiter => ",")}"
                  %td
                    = "#{number_to_currency(order.try(:balance), :unit => "₱", :separator => ".", :delimiter => ",")}"
                  %td
                    = link_to "<button class='btn btn-sm waves-effect waves-light lbl-remove-item'>View</button>".html_safe, order_product_path(order.id)
= stylesheet_link_tag  'cart.css'